function [ddthetaN,dthetaN,thetaN,theta,dtheta,ddtheta]=SolveThetaN(alpha,dalpha,ddalpha,dlambda,...
          PHI,dPHI,ddPHI,ddphi0,dtheta,dthetaN,thetaN,theta)
           %输入此时刻dthetaN、thetaN和dtheta，输出下一时刻dthetaN、thetaN和theta
global USR

temp11=(USR.N*USR.m+(USR.e)'*(USR.Stheta).^2*USR.mu*USR.e);
temp12=-(USR.e)'*USR.Stheta*USR.Ctheta*USR.mu*USR.e;
temp21=temp12;
temp22=USR.N*USR.m+(USR.e)'*(USR.Ctheta).^2*USR.mu*USR.e;
Mp=inv([temp11,temp12;temp21,temp22]);
    
Mp_cell=mat2cell(Mp,[1 1],[1 1]);
m11=Mp_cell{1,1};
m12=Mp_cell{1,2};
m21=Mp_cell{2,1};
m22=Mp_cell{2,2};

K1=m11*(USR.e)'*(USR.Stheta)^2*USR.mu-m12*(USR.e)'*USR.Stheta*USR.Ctheta*USR.mu;
K2=(-1)*m11*(USR.e)'*USR.Stheta*USR.Ctheta*USR.mu+m12*(USR.e)'*(USR.Ctheta).^2*USR.mu;
K3=m21*(USR.e)'*(USR.Stheta)^2*USR.mu-m22*(USR.e)'*USR.Stheta*USR.Ctheta*USR.mu;
K4=m21*(USR.e)'*USR.Stheta*USR.Ctheta*USR.mu-m22*(USR.e)'*(USR.Ctheta)^2*USR.mu;
K5=(-1)*USR.m*USR.L*USR.Stheta*USR.K*USR.e-USR.L*USR.Stheta*USR.K*(USR.Stheta)^2*USR.mu*...
       USR.e-USR.L*USR.Ctheta*USR.K*USR.Stheta*USR.Ctheta*USR.mu*USR.e;
K6=USR.m*USR.L*USR.Ctheta*USR.K*USR.e+USR.L*USR.Stheta*USR.K*USR.Stheta*USR.Ctheta*...
    USR.mu*USR.e+USR.L*USR.Ctheta*USR.K*USR.Ctheta*USR.Ctheta*USR.mu*USR.e;

A1=(-1)*USR.L*(USR.Stheta)^2*USR.mu*(USR.K)'*USR.Stheta-USR.L*USR.Stheta*USR.Ctheta*...
    USR.mu*(USR.K)'*USR.Ctheta;
A2=(-1)*USR.L*(USR.Stheta)^2*USR.mu*(USR.K)'*USR.Ctheta+USR.L*USR.Stheta*USR.Ctheta*...
    USR.mu*(USR.K)'*USR.Stheta;
A4=USR.L*USR.Stheta*USR.Ctheta*USR.mu*(USR.K)'*USR.Stheta+USR.L*(USR.Ctheta)^2*USR.mu*...
    (USR.K)'*USR.Ctheta;
A5=USR.L*USR.Stheta*USR.Ctheta*USR.mu*(USR.K)'*USR.Ctheta-USR.L*(USR.Ctheta)^2*...
    USR.mu*(USR.K)'*USR.Stheta;

Kx=-USR.L*USR.Stheta*USR.K-K5*m11*(USR.e)'-K6*m21*(USR.e)';
Ky=USR.L*USR.Ctheta*USR.K-K5*m12*(USR.e)'-K6*m22*(USR.e)';

Mtheta=USR.J*USR.IN+USR.m*(USR.L)^2*USR.Stheta*USR.V*USR.Stheta+USR.m*(USR.L)^2*...
       USR.Ctheta*USR.V*USR.Ctheta-USR.L*USR.Stheta*USR.K*A1+USR.L*USR.Ctheta*USR.K*...
       A4+USR.L*K5*K1*(USR.K)'*USR.Stheta-USR.L*K5*K2*(USR.K)'*USR.Ctheta+USR.L*K6*K3*...
       (USR.K)'*USR.Stheta+USR.L*K6*K4*(USR.K)'*USR.Ctheta+USR.LAMBDA1;
Wtheta=USR.m*(USR.L)^2*USR.Stheta*USR.V*USR.Ctheta-USR.m*(USR.L)^2*USR.Ctheta*USR.V*...
       USR.Stheta-USR.L*USR.Stheta*USR.K*A2+USR.L*USR.Ctheta*USR.K*A5+USR.L*K5*K1*...
       (USR.K)'*USR.Ctheta+USR.L*K5*K2*(USR.K)'*USR.Stheta+USR.L*K6*K3*(USR.K)'*...
       USR.Ctheta-USR.L*K6*K4*(USR.K)'*USR.Stheta;
Vtheta=USR.LAMBDA2+USR.LAMBDA3*diag(abs(dtheta));
Ntheta=(USR.L*USR.Stheta*USR.K*USR.Stheta*USR.Ctheta*USR.mu+USR.L*USR.Ctheta*USR.K*...
       (USR.Ctheta)^2*USR.mu-K5*K2+K6*K4)*diag(dtheta);
Ptheta=(USR.L*USR.Stheta*USR.K*(USR.Stheta)^2*USR.mu+USR.L*USR.Ctheta*USR.K*USR.Stheta*...
        USR.Ctheta*USR.mu+K5*K1+K6*K3)*diag(dtheta);
    
% ddthetaN=(-2)*(USR.e)'*Mtheta*USR.H*dPHI/(USR.e'*Mtheta*USR.e)*dalpha*dlambda-(USR.e)'*...
%      Mtheta*USR.H*ddPHI/((USR.e)'*Mtheta*USR.e)*alpha*(dlambda)^2-(USR.e)'*Mtheta*USR.H*...
%      PHI/((USR.e)'*Mtheta*USR.e)*ddalpha-(USR.e)'*Mtheta*USR.H*PHI/((USR.e)'*Mtheta*...
%      USR.e)*alpha*ddlambda-(USR.e)'*Mtheta*USR.H*USR.e_/((USR.e)'*Mtheta*USR.e)*...
%      ddphi0-USR.e'/(USR.e'*Mtheta*USR.e)*(Wtheta*(dtheta).^2+Vtheta*dtheta+Ntheta*...
%      (-USR.e*USR.RiverVx)+Ptheta*(-USR.e*USR.RiverVy)+Kx*(USR.fd1x+USR.fd2x)+Ky*...
%      (USR.fd1y+USR.fd2y));

ddthetaN=-(USR.e'/(USR.e'*Mtheta*USR.e))*(Wtheta*dtheta.^2+Vtheta*dtheta-Ntheta*...
                  (USR.e*USR.RiverVx)-Ptheta*(USR.e*USR.RiverVy)+Kx*(USR.fd1x+USR.fd2x)...
                  +Ky*(USR.fd1y+USR.fd2y))-(USR.e'*Mtheta*USR.H*PHI/(USR.e'*Mtheta*USR.e))*...
                  ddalpha-(2*USR.e'*Mtheta*USR.H*dPHI/(USR.e'*Mtheta*USR.e))*dalpha-...
                   (USR.e'*Mtheta*USR.H*ddPHI/(USR.e'*Mtheta*USR.e))*alpha-(USR.e'*Mtheta*...
                   USR.H*USR.e_/(USR.e'*Mtheta*USR.e))*ddphi0;

%计算下一时刻
dthetaN=dthetaN+ddthetaN*USR.tStep;
thetaN=thetaN+dthetaN*USR.tStep;

% thetaTest=USR.e*thetaN+USR.H*alpha*PHINext+USR.H*USR.e_*phi0;

ddtheta=USR.e*ddthetaN+ddalpha*USR.H*PHI+2*dalpha*USR.H*dPHI+...
                  alpha*USR.H*ddPHI+USR.H*USR.e_*ddphi0;
dtheta=dtheta+ddtheta*USR.tStep;
theta=theta+dtheta*USR.tStep;

% 第三行PHI*alpha*ddlambda 和第六行VxVy前面都多了dPx dPy
end